import { projectPaths } from '../src/projectPaths.js';
export const origin = 'https://hikari-brandan.vercel.app';
export const identity = {
  name: 'Hikari Brandan', jobTitle: 'AI Product Developer',
  description: 'AI Product Developer and product builder raised in Seattle and based in Córdoba, Argentina. Available remotely; native English and Spanish.',
  image: '/assets/mobile/hikari-roots-portrait.jpg',
  sameAs: ['https://www.linkedin.com/in/daiske-brandan-726656323/', 'https://github.com/hikaribrandan3-code'],
};
export const pages = [
  { key:'ugc', name:'UGC Camera', title:'UGC Camera — Browser-Based Branded Camera Platform | Hikari Brandan',
    summary:'UGC Camera is a branded browser camera for businesses. Customers tap NFC or scan QR to capture and share photos without installing an app.',
    role:'Hikari Brandan designed and built the product, browser camera experience, NFC and QR entry flows, mobile interactions and sharing, and carried out device testing and debugging.',
    image:'/assets/desktop/ugc-salad-spot.webp', imageAlt:'Salad Spot branded food-photo camera preview from UGC Camera',
    type:'WebApplication', productUrl:'https://www.ugccamera.com/', category:'MultimediaApplication',
    debug:'Resizing and rotating stickers required overly precise touches. I compared the controls with Instagram and expanded the interactive touch area without unnecessarily enlarging the visible control.',
  },
  { key:'menutap', name:'MenuTap', title:'MenuTap — NFC Restaurant Table Hub | Hikari Brandan',
    summary:'MenuTap is an NFC restaurant table hub giving customers one tap access to a menu, Wi-Fi, Google reviews, games and social links.',
    role:'Hikari Brandan designed and built the physical-to-digital product and restaurant web experience, reusing restaurant functionality from FoodSpot and testing the customer-facing flow.',
    image:'/assets/desktop/menutap-sticker.webp', imageAlt:'Physical MenuTap NFC tabletop artwork showing menu, Wi-Fi, reviews, games and socials',
    type:'WebApplication', productUrl:'https://www.foodspotmobile.com/t/foodspot-demo', category:'BusinessApplication',
  },
  { key:'foodspot', name:'FoodSpot Mobile', title:'FoodSpot Mobile — Restaurant Commerce SaaS & UGC Receipt | Hikari Brandan',
    summary:'FoodSpot Mobile was a restaurant commerce SaaS project spanning dashboards, menus, inventory and customer engagement. A populated demo preserves its delivered-order UGC Receipt experiment.',
    role:'Hikari Brandan built the restaurant product and customer experience, including operations screens, ordering and the post-delivery photo invitation. The current Smash Burger installation is a demonstration, not an operating restaurant.',
    image:'/assets/mobile/foodspot-receipt-poster.jpg', imageAlt:'FoodSpot Mobile delivered-order receipt and customer photo invitation in the Smash Burger demo',
    type:'WebApplication', productUrl:'https://foodspotapp-gold.vercel.app/smash-burger-demo/home', category:'BusinessApplication',
  },
  { key:'mac', name:'Independent macOS App Suite', title:'Independent macOS App Suite — Local AI & Desktop Experiments | Hikari Brandan',
    summary:'Five independent Mac projects by Hikari Brandan: iVoz, iOrganize, Screen Bridge, iStats and iBrain. Explore real app interfaces, public source, product decisions and known limitations.',
    role:'Hikari Brandan built independent desktop utilities and experiments for his own workflow, working on local processing, native interfaces, shortcuts, permissions and debugging.',
    image:'/assets/desktop/ivoz-window-real.webp', imageAlt:'Actual iVoz macOS dictation application window', type:'CreativeWork',
    debug:'Some hotkeys were not recognized consistently, and microphone permission could be requested again after relaunch. I tested different shortcuts and repeated macOS launch and permission scenarios to improve those flows.',
  },
  { key:'autobarber', name:'The Auto Barber', title:'The Auto Barber — Automotive Restyling Business | Hikari Brandan',
    summary:'Hikari Brandan’s former Seattle-area automotive restyling business, with supplied six-figure revenue history and 165+ Google reviews. Business execution, operations and customer experience.',
    role:'Hikari Brandan operated the business and handled sales, marketing, operations, hiring, employee training and customer experience.',
    image:'/assets/mobile/autobarber-workshop.webp', imageAlt:'Hikari Brandan working in the Auto Barber workshop wearing its branded apron', type:'Organization',
  },
  { key:'engineering', name:'Build Notes', title:'Build Notes — Product Decisions, Testing & Debugging | Hikari Brandan',
    summary:'Hikari Brandan’s workflow: problem, research, think, PRD, build with AI, test, break it, audit and fix, ship. Factual notes and examples from his products.',
    role:'Written by Hikari Brandan from his product development and debugging experience.',
    image:'/assets/desktop/ivoz-window-real.webp', imageAlt:'Actual iVoz app, one of the products discussed in Hikari Brandan’s Build Notes', type:'CreativeWork',
    debug:'When login appeared to complete but downstream operations failed, I inspected the callback URL and browser console, then traced Supabase Edge Function logs and database access. In some cases, row-level security or data access was blocking the operation.',
  },
].map(page => ({ ...page, path:projectPaths[page.key] }));
